name: pos_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  device_info_plus: ^12.3.0
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^10.0.0
  focus_detector: ^2.0.1
  get_it: ^9.2.0
  go_router: ^17.0.1
  google_sign_in: ^6.2.1
  image_picker: ^1.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/logo/
